# Generated by Django 5.1.1 on 2024-11-05 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('pode_banir_usuario', models.BooleanField(default=False)),
                ('pode_conversar_com_usuario', models.BooleanField(default=False)),
                ('pode_visualizar_categorias', models.BooleanField(default=False)),
                ('pode_criar_categorias', models.BooleanField(default=False)),
                ('pode_editar_categorias', models.BooleanField(default=False)),
                ('pode_remover_categorias', models.BooleanField(default=False)),
                ('pode_visualizar_produtos', models.BooleanField(default=False)),
                ('pode_criar_produtos', models.BooleanField(default=False)),
                ('pode_editar_produtos', models.BooleanField(default=False)),
                ('pode_remover_produtos', models.BooleanField(default=False)),
                ('pode_visualizar_estoques', models.BooleanField(default=False)),
                ('pode_criar_estoques', models.BooleanField(default=False)),
                ('pode_editar_estoques', models.BooleanField(default=False)),
                ('pode_remover_estoques', models.BooleanField(default=False)),
                ('pode_visualizar_promocoes', models.BooleanField(default=False)),
                ('pode_criar_promocoes', models.BooleanField(default=False)),
                ('pode_editar_promocoes', models.BooleanField(default=False)),
                ('pode_remover_promocoes', models.BooleanField(default=False)),
                ('pode_criar_transportadora', models.BooleanField(default=False)),
                ('pode_editar_transportadora', models.BooleanField(default=False)),
                ('pode_remover_transportadora', models.BooleanField(default=False)),
                ('pode_visualizar_avaliacoes', models.BooleanField(default=False)),
                ('pode_remover_avaliacoes', models.BooleanField(default=False)),
                ('pode_visualizar_cupons', models.BooleanField(default=False)),
                ('pode_criar_cupons', models.BooleanField(default=False)),
                ('pode_editar_cupons', models.BooleanField(default=False)),
                ('pode_remover_cupons', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompraProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('estado', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=15)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=100, null=True)),
                ('numero', models.CharField(blank=True, max_length=8, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('is_principal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email_recuperacao', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('is_ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('inscricao_estadual', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('preco_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('endereco', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('compra_produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.compraproduto')),
                ('nota', models.CharField(blank=True, choices=[('⭐', '⭐'), ('⭐⭐', '⭐⭐'), ('⭐⭐⭐', '⭐⭐⭐'), ('⭐⭐⭐⭐', '⭐⭐⭐⭐'), ('⭐⭐⭐⭐⭐', '⭐⭐⭐⭐⭐')], max_length=5, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('forma_pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.formapagamento')),
                ('numero', models.CharField(max_length=20)),
                ('validade', models.DateField()),
                ('codigo_seguranca', models.CharField(max_length=10)),
                ('nome_dono', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Pix',
            fields=[
                ('forma_pagamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.formapagamento')),
                ('chave', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='compraproduto',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compra'),
        ),
        migrations.CreateModel(
            name='CupomCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compra')),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cupom')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='cupons',
            field=models.ManyToManyField(through='app.CupomCompra', to='app.cupom'),
        ),
        migrations.AddField(
            model_name='compra',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.endereco'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('AGUARDANDO_VERIFICACAO', 'Aguardando Verificação'), ('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('BANIDO', 'Banido')], default='ATIVO', max_length=25)),
                ('data_final_suspensao', models.DateTimeField(blank=True, null=True)),
            ],
            bases=('app.pessoa',),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.chamado')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('localizacao', models.CharField(blank=True, max_length=70, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
        migrations.AddField(
            model_name='compraproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto'),
        ),
        migrations.CreateModel(
            name='ProdutoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='categorias',
            field=models.ManyToManyField(through='app.ProdutoCategoria', to='app.categoria'),
        ),
        migrations.CreateModel(
            name='PromocaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
                ('promocao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.promocao')),
            ],
            options={
                'unique_together': {('produto', 'promocao')},
            },
        ),
        migrations.AddField(
            model_name='promocao',
            name='produtos',
            field=models.ManyToManyField(through='app.PromocaoProduto', to='app.produto'),
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('compra_produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.compraproduto')),
                ('codigo_rastreio', models.CharField(blank=True, max_length=100, null=True)),
                ('data_postado', models.DateTimeField(blank=True, null=True)),
                ('data_transito', models.DateTimeField(blank=True, null=True)),
                ('data_recebido', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao_transito', models.DateTimeField(blank=True, null=True)),
                ('data_devolucao_recebido', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AGUARDANDO_PAGAMENTO_COMPRA', 'Aguardando Pagamento da Compra'), ('EM_PREPARO', 'Em Preparo'), ('POSTADO', 'Postado'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue'), ('NAO_ENTREGUE', 'Não Entregue'), ('D_AGUARDANDO_TRANSPORTADORA', 'Devolução Aguardando Transportadora'), ('D_EM_TRANSITO', 'Devolução em Trânsito'), ('DEVOLVIDO', 'Devolvido')], max_length=30, null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.transportadora')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.pessoa')),
                ('acesso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.acesso')),
            ],
            bases=('app.pessoa',),
        ),
        migrations.AddField(
            model_name='chamado',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcionario'),
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='chamado',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='compraproduto',
            unique_together={('compra', 'produto')},
        ),
        migrations.CreateModel(
            name='CarrinhoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
                ('carrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.carrinho')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='produtos',
            field=models.ManyToManyField(through='app.CarrinhoProduto', to='app.produto'),
        ),
        migrations.CreateModel(
            name='ListaDesejos',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.usuario')),
                ('produtos', models.ManyToManyField(to='app.produto')),
            ],
        ),
    ]
