# Generated by Django 5.1.1 on 2024-12-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='estado',
            field=models.CharField(choices=[('AGUARDANDO_PAGAMENTO_COMPRA', 'Aguardando Pagamento da Compra'), ('EM_PREPARO', 'Em Preparo'), ('POSTADO', 'Postado'), ('EM_TRANSITO', 'Em Trânsito'), ('ENTREGUE', 'Entregue')], default='AGUARDANDO_PAGAMENTO_COMPRA', max_length=30),
        ),
    ]
