# Generated by Django 5.1.1 on 2024-12-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categorias',
        ),
        migrations.AddField(
            model_name='categoria',
            name='produtos',
            field=models.ManyToManyField(to='app.produto'),
        ),
        migrations.DeleteModel(
            name='ProdutoCategoria',
        ),
    ]
