# Generated by Django 5.1.1 on 2024-11-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='nome',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
