# Generated by Django 5.1.1 on 2024-11-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_chamado_usuario_alter_compra_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
