# Generated by Django 5.1.1 on 2024-11-25 22:30

from django.db import migrations


def criar_funcionalidades_mysql(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        ### CRIEI ESSAS FUNCIONALIDADES APENAS PARA TESTAR, NÃO SÃO AS FINAIS

        # Procedure
        cursor.execute("""
        CREATE PROCEDURE IF NOT EXISTS obter_nomes_usuarios()
        BEGIN
            SELECT username AS usuarios_nomes FROM app_users;
        END;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_acesso_options_alter_avaliacao_options_and_more'),
    ]

    operations = [
        migrations.RunPython(criar_funcionalidades_mysql)
    ]
