# Generated by Django 5.1.1 on 2024-12-03 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_entrega_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='produtos',
            field=models.ManyToManyField(through='app.CompraProduto', to='app.produto'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.endereco'),
        ),
    ]
