# Generated by Django 5.1.1 on 2024-11-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_endereco_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('LIVRARIA', 'Livraria'), ('PAPELARIA', 'Papelaria')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='cep', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(default='coco', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(default='xixi', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='nome',
            field=models.CharField(default='nnnnnn', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=100),
        ),
    ]
