# Generated by Django 5.1.1 on 2024-11-25 22:41

from django.db import migrations


def criar_view(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        ### CRIEI ESSAS FUNCIONALIDADES APENAS PARA TESTAR, NÃO SÃO AS FINAIS

        # View
        cursor.execute("""
        CREATE VIEW nomes AS
        SELECT username
        FROM auth_user;
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20241125_1930'),
    ]

    operations = [
        migrations.RunPython(criar_view)
    ]
