# Generated by Django 5.1.1 on 2024-12-03 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cupom_compras_alter_entrega_transportadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='transportadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.transportadora'),
        ),
    ]
