# Generated by Django 5.1.1 on 2024-12-03 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_entrega_transportadora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportadora',
            old_name='preco_km',
            new_name='preco',
        ),
    ]
